### ISSUE TITLE
`ExtraRedeemers` error when the index pointer is correct

### ISSUE THREAD

**Issue by MartinSchere** [CardanoSolutions/ogmios#275] opened 2022-10-22 18:01 UTC
#### What Git revision are you using? 

[v5.3.0](https://github.com/CardanoSolutions/ogmios/releases/tag/v5.3.0) (I am not 100% sure, sorry)

#### What operating system are you using, and which version?

- [ ] Linux / Ubuntu
- [ ] Linux / Other
- [x] OSX
- [ ] Windows

#### Describe what the problem is?

We are receiving the following error:

```
ExtraRedeemersError: ["spend:5"]
```
 with `evaluateTx` with the following transaction

```
84a900868258200469d5f4c7b3c70eb77cab859fb505ad00bba172e2df40a88cb43a626da788e30382582067e908ba3d8c84ddd3c26c4b0fcb754fb1c7a484789d5e23105dc83585562c6f008258206b46b534199721370ffe0559e2899595c0c63a285f1c70455ac5503eec30ff5e03825820bd8ec4472a6ddd8f4fa382d61302f474029cd5d7949537c90bf5242f2c281c8501825820be4923e2c18a4c743d654fdd44535d4b346fadda39e54ee81d596b1ca33e4c5c03825820c15e8c6a5716d76d0daa42263f1e05adc71e08ac352d23ec91fee8333fa72c210001828258390137c57f178da9dbc7b0ab610748b98a4fec56a1687230c6088a9f80d79678ac066379cdaf93f40669bf2a0e6b86cfe542f949f95e26533c6a1a05f5e1008258390137c57f178da9dbc7b0ab610748b98a4fec56a1687230c6088a9f80d79678ac066379cdaf93f40669bf2a0e6b86cfe542f949f95e26533c6a821a01137badb1581c0af69d267670bfc1bea2c591b95131688b201f499310360e52cee812a2504d6f636f7373694c616e64303439383001504d6f636f7373694c616e64303737323701581c11ebbfbfd62985cbae7330b95488b9dcf17ecb5e728442031362ad81a44d48756e677279436f7723323131014e48756e677279436f772333363836014e48756e677279436f772338323732014e48756e677279436f77233837363201581c13e3f9964fe386930ec178d12a43c96a7f5841270c2146fc509a9f3ea253436c61794e6174696f6e5069746368373037340154436c61794e6174696f6e5069746368333137383701581c27d4e0b1da659588e68bf785ba932db5243503a22329a8d43a0d07bfa2514e4d4b526174434e4654436f6e3337343201514e4d4b526174434e4654436f6e3430313301581c39fbbb94ab418566b5a5d5b0ba9df90074090ccf27ebfc77221b56bfa1514772656173796d6f6e6b6579733038353201581c4bf184e01e0f163296ab253edd60774e2d34367d0e7b6cbc689b567da1535061766961506c7573313135506c757331333001581c4c3f8a1773b7813e537a75f7b1b2897996bdc0e1d6d7d0c11252e252a1504d6f636f73736949746f32313834333301581c62afb32c355614608390ccfd007f87fb06844cec373dba4ce8272184a154426c6f636b4f776c73634e4654636f6e3030373101581c7a3eec65a77b198fd78916d074d3681760d22c885e5ad2835d071de4a15053616372656446656d6d65733235353001581c94f7d4a9be15ae6da89d1a3f8e1089106dc92296241fa5c017eabd62b82e49736c617663617434350149736c617663617436300149736c617663617438350149736c617663617438360149736c617663617439360149736c61766361743939014a736c6176636174313934014a736c6176636174323031014a736c6176636174353339014a736c6176636174353430014a736c6176636174353431014a736c6176636174353434014a736c6176636174353437014a736c6176636174353439014a736c6176636174353533014a736c6176636174373033014a736c6176636174373130014a736c6176636174373336014a736c6176636174373534014a736c6176636174373630014a736c6176636174393337014a736c6176636174393634014b736c617663617431313238014b736c617663617431313331014b736c617663617431313333014b736c617663617431313533014b736c617663617431333330014b736c617663617431343038014b736c617663617431343139014b736c617663617431373239014b736c617663617431383733014b736c617663617432323539014b736c617663617432323630014b736c617663617432373632014b736c617663617432383733014b736c617663617432383734014b736c617663617433313230014b736c617663617433323239014b736c617663617433333233014b736c617663617433373634014b736c617663617434303537014b736c617663617434323635014b736c617663617434343131014b736c617663617434343135014b736c617663617434343136014b736c61766361743434343301581c9d3f45e10a42a76b7da76c9b820a6e3a47e610d8b046ba53beeb9729a6443036393301443132373901443234333301443339343701443530323701443532343801581ca5bb0e5bb275a573d744a021f9b3bff73595468e002755b447e01559a356484f534b5943617368477261623030303031333733390156484f534b5943617368477261623030303235323432390156484f534b59436173684772616230303032353830383201581caf267bd857e9d78fdb5fa05e91a342907518e30b0211cdf2b9c7cd00a64f416e657461416e67656c7332373131014f416e657461416e67656c7334383532014f416e657461416e67656c7336303830014f416e657461416e67656c7336333037014f416e657461416e67656c7336343832014f416e657461416e67656c733733303001581cd0db9adb5fe3083b7c59c4fa55c8acaa70f96976bd9ade2db52e1a79a355576561726543617264616e6f5768616c65313837360155576561726543617264616e6f5768616c65333533380155576561726543617264616e6f5768616c653833343601581cee6da4b71e0913cbebec02edc23653f9b970af69324fdddfed1285d9a34d53706163654170653033393737014d53706163654170653034323430014d5370616365417065303630313401581cef76f6f0b3558ea0aaad6af5c9a5f3e5bf20b393314de747662e8ce9ae4a506f6c79506565723436014b506f6c7950656572313433014b506f6c7950656572353330014c506f6c795065657231373630014c506f6c795065657233333439014c506f6c795065657234323134014c506f6c795065657234343838014c506f6c795065657235303831014c506f6c795065657235333339014c506f6c795065657235383137014c506f6c795065657235383534014c506f6c795065657236303731014c506f6c795065657238323635014c506f6c79506565723839313301581cfa669150ad134964e86b2fa7275a12072f61b438d0d44204d3a2f967a44a426164466f7830323634014a426164466f7831383430014a426164466f7831393637014a426164466f783531393901021a00045b5d031a0476d4d9081a0476ca4d0b582000000000000000000000000000000000000000000000000000000000000000000d818258204c31b14c70ec658cb7c3978f8e63fe5d1715233348864fbed9eec3e0011fc009000e81581c37c57f178da9dbc7b0ab610748b98a4fec56a1687230c6088a9f80d712818258209a32459bd4ef6bbafdeb8cf3b909d0e3e2ec806e4cc6268529280b0fc1d06f5b00a300818258200000000037c57f178da9dbc7b0ab610748b98a4fec56a1687230c6088a9f80d7584000f899d39b17fd5d66c192c4b50d343e42f7235b30504c8ae7619f93c828dc6dce4568dd69177c551828492d777a6727fd66c2fbccbda8c2aeed92032c99790a049fd8799f581c37c57f178da9dbc7b0ab610748b98a4fec56a1687230c6088a9f80d79fd8799fd8799fd8799f581c3342ca8c073a11b7664bd105123353e79c01116cc465915133fdcf75ffd8799fd8799fd8799f581cd6c5f6f7562142b9815eacc31a3a1579991452e860aaf60573722018ffffffffa140d8799f00a1401a001e8480ffffd8799fd8799fd8799f581c70e60f3b5ea7153e0acc7a803e4401d44b8ed1bae1c7baaad1a62a72ffd8799fd8799fd8799f581c1e78aae7c90cc36d624f7b3bb6d86b52696dc84e490f343eba89005fffffffffa140d8799f00a1401a001e8480ffffd8799fd8799fd8799f581c37c57f178da9dbc7b0ab610748b98a4fec56a1687230c6088a9f80d7ffd8799fd8799fd8799f581c9678ac066379cdaf93f40669bf2a0e6b86cfe542f949f95e26533c6affffffffa1581cf0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9ad8799f00a14861646167616d657301ffffffffff0581840005d87980821b00000001000000001b0000000100000000f5f6
```

If you decode the transaction using cbor.me, the 5th input is `c15e8c6a5716d76d0daa42263f1e05adc71e08ac352d23ec91fee8333fa72c21` which outputs to the jpg.store script. My initial thought was that the output was spent by another transaction (`BadInputsUTxO` in phase 1), but @KtorZ says that it is not the case.

#### What should be the expected behavior?

A correct evaluation of the transaction resulting in the execution units.

**Comment by KtorZ** [comment] 2022-10-22 22:39
This error has two sources:

1. Either, the script to which points the redeemer is missing. 
2. Or, the script pointed by the redeemer uses an unknown language. 

(1) seems unlikely in your case because of the reference input which correctly points to a script. I believe it to be the right one. 

(2) seems plausible if you're using `v5.3.0`; the use of reference inputs and thus plutus:v2 was added in v5.5.* and onwards. It's quite plausible that a Babbage transaction correctly parses as an Alonzo transaction, but the reference inputs and plutus:v2 would be unknown of Ogmios at this version. 

--- 

Having said that... I checked on v5.5.6 and I also get the same error. The input is obviously missing and, this seems to be the issue here. If I provide the input as `additionalUtxoSet`, the evaluation moves further to:

```
> evaluateTx("...", [[{txId:"c15e8c6a5716d76d0daa42263f1e05adc71e08ac352d23ec91fee8333fa72c21",index:0},{address:"addr1zxgx3far7qygq0k6epa0zcvcvrevmn0ypsnfsue94nsn3tvpw288a4x0xf8pxgcntelxmyclq83s0ykeehchz2wtspks905plm",value:{coins:100000000},datumHash:"c31d170c871e206b81696bc77c294276a03237a7f5ba15c66082320965214b0b"}]])
CannotCreateEvaluationContextError: {"reason":"Unknown transaction input (missing from UTxO set): 0469d5f4c7b3c70eb77cab859fb505ad00bba172e2df40a88cb43a626da788e3#3"}
```

I reckon that the error is a bit misleading here but that's sadly something I have little control over with Ogmios. Would be better to fix this upstream in the ledger tools.

**Comment by KtorZ** [comment] 2022-10-22 23:22
I can also confirm that this is indeed the behavior of the server when a redeemer points to an unknown input. 

The TypeScript client implementation has been fixed in: https://github.com/CardanoSolutions/ogmios/commit/959ffcb658b2374162390cd837b7d3306d6e5419

And as far as I can tell, the server works as intended. Perhaps to add on the wishlist for v6.0.0: improve errors for transaction evaluation and submission.

**Closed by KtorZ** 2022-10-22 23:22 UTC

**Comment by MartinSchere** [comment] 2022-10-22 23:56
@KtorZ The transaction input is on the chain:

https://cardanoscan.io/transaction/0469d5f4c7b3c70eb77cab859fb505ad00bba172e2df40a88cb43a626da788e3?tab=utxo

That is the one shown in the error: 
```
CannotCreateEvaluationContextError: {"reason":"Unknown transaction input (missing from UTxO set): 0469d5f4c7b3c70eb77cab859fb505ad00bba172e2df40a88cb43a626da788e3#3"}
```

However, that is not where the redeemer points to. The redeemer points to the 5th input, which is `c15e8c6a5716d76d0daa42263f1e05adc71e08ac352d23ec91fee8333fa72c21#0`. And that is confirmed on-chain too:

https://cardanoscan.io/transaction/c15e8c6a5716d76d0daa42263f1e05adc71e08ac352d23ec91fee8333fa72c21?tab=utxo

So I guess I have two questions:
1. Why is the error pointing to another input when the redeemer points to the one on index 5?
2. If both are confirmed on-chain, why is it `UnkownInput`?

My hypothesis is that the inputs are sorted differently at some point in the building process:
```py
[
      ['0469D5F4C7B3C70EB77CAB859FB505AD00BBA172E2DF40A88CB43A626DA788E3', 3],
      ['67E908BA3D8C84DDD3C26C4B0FCB754FB1C7A484789D5E23105DC83585562C6F', 0],
      ['6B46B534199721370FFE0559E2899595C0C63A285F1C70455AC5503EEC30FF5E', 3],
      ['BD8EC4472A6DDD8F4FA382D61302F474029CD5D7949537C90BF5242F2C281C85', 1],
      ['BE4923E2C18A4C743D654FDD44535D4B346FADDA39E54EE81D596B1CA33E4C5C', 3],
      ['C15E8C6A5716D76D0DAA42263F1E05ADC71E08AC352D23EC91FEE8333FA72C21', 0],
 ]
```
However, unless they are sorted backwards, I do not see how `['0469D5F4C7B3C70EB77CAB859FB505AD00BBA172E2DF40A88CB43A626DA788E3', 3]` would be the last input. Which seems strange

**Comment by KtorZ** [comment] 2022-10-23 09:12
@MartinSchere let me clarify:

- The input referred to by ['C15E8C6A5716D76D0DAA42263F1E05ADC71E08AC352D23EC91FEE8333FA72C21', 0] is **not** on-chain anymore, it was spent already. Asking the node directly about this gives nothing:

  ```
  ogmios> await utxo([{ txId: "c15e8c6a5716d76d0daa42263f1e05adc71e08ac352d23ec91fee8333fa72c21", index: 0 }])
  []
  ```

  [kupo](https://github.com/CardanoSolutions/kupo) confirms it, if I start indexing from just before the transaction happens:

  ```
  $ kupo \
      --node-config /usr/local/share/cardano/network/mainnet/cardano-node/config.json \
      --node-socket /tmp/node.socket \
      --workdir . \
      --match "*@c15e8c6a5716d76d0daa42263f1e05adc71e08ac352d23ec91fee8333fa72c21" \
      --since "73982561.14fb01fe1b7640c39f2e49adb8c3afbe80d5c1712d99776bf9eebc9b8961d997"
  ```

  wait a couple of seconds and then try to query it:

  ```
  curl "http://127.0.0.1:1442/matches/0@c15e8c6a5716d76d0daa42263f1e05adc71e08ac352d23ec91fee8333fa72c21" | jq
  [
    {
      "transaction_index": 5,
      "transaction_id": "c15e8c6a5716d76d0daa42263f1e05adc71e08ac352d23ec91fee8333fa72c21",
      "output_index": 0,
      "address": "addr1zxgx3far7qygq0k6epa0zcvcvrevmn0ypsnfsue94nsn3tvpw288a4x0xf8pxgcntelxmyclq83s0ykeehchz2wtspks905plm",
      "value": {
        "coins": 100000000,
        "assets": {}
      },
      "datum_hash": "c31d170c871e206b81696bc77c294276a03237a7f5ba15c66082320965214b0b",
      "script_hash": null,
      "created_at": {
        "slot_no": 73982607,
        "header_hash": "a7bce68f5f2d761fc01470ac54e8f37a6bfb95327e85e47ae449873058959f47"
      },
      "spent_at": {
        "slot_no": 74037241,
        "header_hash": "b1a17e1d26bebeb174f677a3b849aa7620366fda34f6d6666c005b99d59d507d"
      }
    }
  ]
  ```

  As you can see, the input is spent in slot 74037241 (by [c81919f81](https://cardanoscan.io/transaction/c81919f811b130989550237e2b1ea25cb382dcda1ac883c69089e7292ecb7b3a?tab=utxo)).

- Thus, because (a) the input to which the redeemer points to is missing (that is, the 5th input of the transaction) and because (b) it is the one actually bringing the requirement for the script in scope, the ledger complains about an "extra redeemer". Somehow, it seems like it resolves scripts before resolving inputs in the evaluation tool.

- Thus what I did above was to provide the missing input as `additionalUtxoSet` which instrument Ogmios to provide this handcrafted UTxO to the ledger for evaluation; I did so by reusing the data from the original source; as if it hadn't been spent. This therefore solved the "extra redeemer" error but led to another error, another missing input:

  `0469d5f4c7b3c70eb77cab859fb505ad00bba172e2df40a88cb43a626da788e3#3`

  Now, if we do the same trick with kupo, we'll find out that this other input was spent in slot 74909452 (by [b07d8d6e](https://cardanoscan.io/transaction/b07d8d6e8a804d2132d83eccbf9fd9c783f845a362471adddcdfea15a15c32df?tab=utxo)).

  This time, the error is different however because this input isn't associated with any script, but it's still missing hence "Unknown transaction input". 

I hope this clarifies it.

It'd be nice if:

- Explorers would show whether a UTxO is spent or not. Since we can't query spent tx outputs from the node (because they're gone), we need to resort to an indexer to find out about them. 

- Ogmios would return better errors when it comes to script failures. This is one tightly confusing because somehow the requirement for the script comes before the evaluation tool checks if the input is present. Note that the evaluation tools does not run any phase-1 validations like the real ledger does and this is why we end up in this situation. 

- The evaluation would actually check for the presence of inputs before checking for not-needed scripts or perhaps, return two different errors depending on the scenario.

**Comment by MartinSchere** [comment] 2022-10-23 18:37
Thanks a lot for the explanation!

**Comment by Quantumplation** [comment] 2022-10-26 21:49
> Explorers would show whether a UTxO is spent or not. Since we can't query spent tx outputs from the node (because they're gone), we need to resort to an indexer to find out about them.

You can actually do this on https://cexplorer.io, per my hounding josef about it incessantly!

If you look here:
https://cexplorer.io/tx/c15e8c6a5716d76d0daa42263f1e05adc71e08ac352d23ec91fee8333fa72c21

and look for this icon:
![image](https://user-images.githubusercontent.com/49870/198144951-80a00c19-d88f-4585-a44b-eb3aad76e67c.png)

It will link you backwards *and forwards* in the transaction graph; if that symbol is present, the UTXO has been spent.
