### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by TerminadaPool** [CardanoSolutions/ogmios#318] opened 2023-07-16 08:51 UTC
I am trying to build ogmios (on both amd64 and arm64) but I am getting a build failure at building byron-spec-chain.  (Note: I am able to build cardano-node on both these platforms.)

### What Git revision / release tag are you using?

ogmios v5.6.0
ghc 8.10.7
cabal 3.6.2.0

### If applicable, what are the logs from the server around the occurrence of the problem?

Building library for byron-spec-chain-0.1.0.0..
[1 of 7] Compiling Byron.Spec.Chain.STS.Block ( src/Byron/Spec/Chain/STS/Block.hs, dist/build/Byron/Spec/Chain/STS/Block.o, dist/build/Byron/Spec/Chain/STS/Block.dyn_o )
[2 of 7] Compiling Byron.Spec.Chain.STS.Rule.Bupi ( src/Byron/Spec/Chain/STS/Rule/Bupi.hs, dist/build/Byron/Spec/Chain/STS/Rule/Bupi.o, dist/build/Byron/Spec/Chain/STS/Rule/Bupi.dyn_o )
[3 of 7] Compiling Byron.Spec.Chain.STS.Rule.BBody ( src/Byron/Spec/Chain/STS/Rule/BBody.hs, dist/build/Byron/Spec/Chain/STS/Rule/BBody.o, dist/build/Byron/Spec/Chain/STS/Rule/BBody.dyn_o )
[4 of 7] Compiling Byron.Spec.Chain.STS.Rule.Epoch ( src/Byron/Spec/Chain/STS/Rule/Epoch.hs, dist/build/Byron/Spec/Chain/STS/Rule/Epoch.o, dist/build/Byron/Spec/Chain/STS/Rule/Epoch.dyn_o )
[5 of 7] Compiling Byron.Spec.Chain.STS.Rule.SigCnt ( src/Byron/Spec/Chain/STS/Rule/SigCnt.hs, dist/build/Byron/Spec/Chain/STS/Rule/SigCnt.o, dist/build/Byron/Spec/Chain/STS/Rule/SigCnt.dyn_o )
[6 of 7] Compiling Byron.Spec.Chain.STS.Rule.Pbft ( src/Byron/Spec/Chain/STS/Rule/Pbft.hs, dist/build/Byron/Spec/Chain/STS/Rule/Pbft.o, dist/build/Byron/Spec/Chain/STS/Rule/Pbft.dyn_o )
[7 of 7] Compiling Byron.Spec.Chain.STS.Rule.Chain ( src/Byron/Spec/Chain/STS/Rule/Chain.hs, dist/build/Byron/Spec/Chain/STS/Rule/Chain.o, dist/build/Byron/Spec/Chain/STS/Rule/Chain.dyn_o )

src/Byron/Spec/Chain/STS/Rule/Chain.hs:353:9: error:
    • Couldn't match expected type ‘GHC.Exts.Item
                                      (f0
                                         ((a0 -> Data.Functor.Identity.Identity Hash)
                                          -> BlockHeader
                                          -> Data.Functor.Identity.Identity BlockHeader))’
                  with actual type ‘(Hash -> f1 Hash)
                                    -> BlockHeader -> f1 BlockHeader’
      The type variables ‘f0’, ‘a0’, ‘f1’ are ambiguous
    • In the expression: bhUtxoHash
      In the first argument of ‘Gen.element’, namely
        ‘[bhDlgHash, bhUpdHash, bhUtxoHash]’
      In a stmt of a 'do' block:
        hashLens <- Gen.element [bhDlgHash, bhUpdHash, bhUtxoHash]
    |
353 |         bhUtxoHash
    |         ^^^^^^^^^^
cabal: Failed to build byron-spec-chain-0.1.0.0 (which is required by
test:unit from ogmios-5.6.0). See the build log above for details.

**Comment by KtorZ** [comment] 2023-07-16 09:12
Correct. Upstream dependencies have changed. The build system is supposed to use an immutable snapshot but apparently it still is possible for upstream maintainers to modify an already publish dependency, causing build issues down the line. 

I'll have that fixed next week as I upgrade to the 8.x.x stack.

**Comment by TerminadaPool** [comment] 2023-07-16 11:02
I figured it might be something like that but had no idea how to fix it.  I noticed that cardano-node built cardano-haskell-packages/byron-spec-chain/1.0.0.0 whereas the ogmios build was trying to build 0.1.0.0.

I really need an arm64 version built.  I am trying to compile it on an arm64 machine rather than cross-compiling.  I hope that will work.  (I can build the cardano-node on my arm64 machine.)

**Comment by KtorZ** [comment] 2023-07-16 17:30
You can try adding more constraints in the cabal.project, but I haven't really got much time to check this. Especially because I'll be bumping that dependencies set very soon and I'd like to avoid doing it twice.

**Comment by KtorZ** [comment] 2023-07-20 16:49
I can't reproduce this unfortunately. Either locally or in the continuous integration pipeline. Though I've literally merged ~25K lines changes... so that may have something to do with it 😬 ...

For now, builds are still done against 1.35.x, and I'll get dependencies upgraded to 8.1.x tomorrow. If you want to have look now to tell me whether your problem is fixed, that'd be great. If you want to wait for after 8.1.x is done, that's fine. 

Either way, I'll close the issue once dependencies have been upgraded to 8.1.x as it will become irrelevant.

**Comment by TerminadaPool** [comment] 2023-07-25 09:57
I am now getting this error:
```
src-unix/Ouroboros/Consensus/Storage/IO.hs:28:1: error:
    Could not load module ‘System.Posix.IO.ByteString’
    It is a member of the hidden package ‘unix-bytestring-0.3.7.8’.
    Perhaps you need to add ‘unix-bytestring’ to the build-depends in your .cabal file.
   |
28 | import           "unix-bytestring" System.Posix.IO.ByteString (fdPreadBuf)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build byron-spec-chain-0.1.0.0 (which is required by
test:unit from ogmios-5.6.0). See the build log above for details.
Failed to build ouroboros-consensus-0.1.0.1 (which is required by test:unit
from ogmios-5.6.0 and exe:ogmios from ogmios-5.6.0). See the build log above
for details.
```

I tried following the recommendation to add "unix-bytestring" to the build-depends.  I tried a couple of different locations in the ogmios.cabal file but the build keeps failing at this same point.

Sorry, I am not knowledgeable enough about how to work the cabal magic.  I am trying to learn haskell but unfortunately I am still a complete novice.

Note that I am trying to compile this on an arm64 machine so it could be a problem specific to arm64?  Also, I was compiling with ghc 8.10.7.

**Comment by TerminadaPool** [comment] 2023-07-25 10:15
Oh.  It could be because I was specifically checking out tags/v5.6.0.

I'll try again without git checking out that version.

**Comment by TerminadaPool** [comment] 2023-07-25 21:25
It almost compiled.

I think the problem now is that I need the custom version of libsodium or I need to enable that IOG extra haskell code that allows the use of the standard libsodium.
```
error: undefined reference to 'crypto_vrf_ietfdraft13_publickeybytes'
error: undefined reference to 'crypto_vrf_ietfdraft13_secretkeybytes'
...
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
cabal: Failed to build exe:ogmios from ogmios-0.
Failed to build test:unit from ogmios-0.
```
I will try again after adding the following to cabal.project.local:
```
package cardano-crypto-praos
  flags: -external-libsodium-vrf

package trace-dispatcher
  ghc-options: -Wwarn
```

Unfortunately, my little arm machine is a bit slow.  It is one of these running linux: https://www.solid-run.com/arm-servers-networking-platforms/honeycomb-servers-workstation/

**Comment by KtorZ** [comment] 2023-07-25 22:49
For Ogmios, you don't need any of the fancy VRF crypto indeed (at least until VRF becomes available from within Plutus script, maybe one day if Santa hears us). 

So you can definitely go with that flag.

**Comment by TerminadaPool** [comment] 2023-07-26 07:33
Thanks @KtorZ I got it compiled and it runs on my arm64 relay alongside cardano-node 8.1.1:
```
./ogmios --node-socket '/run/cardano/mainnet-node.socket' --node-config /etc/cardano/mainnet-config.json --host 127.0.0.1 --port 1337
```
```
curl -H 'Accept: application/json' http://localhost:1337/health | jq '.'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   583    0   583    0     0   249k      0 --:--:-- --:--:-- --:--:--  284k
{
  "startTime": "2023-07-26T07:08:15.24776958Z",
  "lastKnownTip": {
    "slot": 98789334,
    "hash": "5161d1690cb3a88f6e2fc177690a79e50a54815cf0a358088bafbf1523f06b1f",
    "blockNo": 9077769
  },
  "lastTipUpdate": "2023-07-26T07:13:46.057469826Z",
  "networkSynchronization": 1,
  "currentEra": "Babbage",
  "metrics": {
    "activeConnections": 0,
    "runtimeStats": {
      "cpuTime": 1482637556,
      "currentHeapSize": 338,
      "gcCpuTime": 901198790,
      "maxHeapSize": 342
    },
    "sessionDurations": {
      "max": 0,
      "mean": 0,
      "min": 0
    },
    "totalConnections": 0,
    "totalMessages": 0,
    "totalUnrouted": 0
  },
  "connectionStatus": "connected",
  "currentEpoch": 426,
  "slotInEpoch": 120534
}
```
It is a thing of beauty.

Now I just need to learn how to code better so that I can make proper use of it.

I first intend to try building a more simple application to grab just the block header details:
* block number
* slot number
* block hash
* pool ID
* prev block hash
* VRF

and then put these into an sqlite database.  (Similar to the cncli sync tool.)

**Comment by KtorZ** [comment] 2023-07-26 07:37
Just FYI, I am currently on a **HEAVY** rework of Ogmios. So the API as it stands now will likely break within the next few days. However, I am already done with most changes on the outer API (the RPC wrappers) and the block metadata (number, hash, etc..). I am mostly fiddling with ledger errors, scripts and metadata these days. 

In principle, the docs is still mostly up-to-date as I updated it along the way, but there may be little quirks left until I am fully done.

**Comment by TerminadaPool** [comment] 2023-07-26 07:48
As a member of the Cardano community, I very much appreciate your efforts, as everyone does.

I am just trying to learn at present.  I figure if I can learn to build something fairly basic then maybe I can contribute more in the future.

**Closed** 2023-07-26 10:25 UTC

**Comment by KtorZ** [comment] 2023-08-03 13:22
@thuannguyen2010, not yet and I am unlikely to look into it before v6.0.0 is released. Something has changed with the [cardano-haskell-packages](https://github.com/input-output-hk/cardano-haskell-packages/) which is causing what used to be a working build to fail because the package snapshot has likely changed. This should be impossible in theory, but in practice, it is possible for someone to push a package in the past which could potentially break working builds. 

This can most likely be solved by pinning the right dependency-set and adding more constraints to the `cabal.project` but I don't have much time at the moment to figure out which ones.

**Comment by thuannguyen2010** [comment] 2023-08-04 04:49
Yeah, I know. I am newbie with Cardano as well as Haskell. Hopefully, you can help to figure out how ```cabal.project``` should be. Thank you.

**Comment by KtorZ** [comment] 2023-08-04 07:42
Had a quick look and here, you're trying to build everything, including the test suite which for some reasons no longer compiles. 

Instead of cabal install or cabal build all, simply do:

`cabal install ogmios:exe:ogmios` or `cabal build ogmios:exe:ogmios`. 

Make sure to build from the **v5.6.1** tag / branch however as I've included a small fix for the cardano-haskell-packages as well.
