### ISSUE TITLE
submitTransaction returns "error":{"size":0,"timeout":0}

### ISSUE THREAD

**Issue by MarcelKlammer** [CardanoSolutions/ogmios#374] opened 2024-03-06 07:05 UTC
### What Git revision / release tag are you using?

v6.1.0 release

### Do you use any client SDK? If yes, which one?

TypeScript

### Describe what the problem is?

Submitting transactions results in code:400 and error:{"size":0,"timeout":0}, which has no information of what actually went wrong.

### What should be the expected behavior?

Some more information on why the transaction failed submit.

**Comment by MarcelKlammer** [comment] 2024-03-06 15:25
Switched to submit via Websocket and getting this hint:

```Some transactions failed to submit (400)
failed:
70b0f089dcda16f724937aca36e057b742f9d41dff5ca4eaf89407bb817ffaf5
The transaction failed because it contains datums not associated with any script or output. This could be because you've left some orphan datum behind, because you've listed the wrong inputs in the transaction or because you've just forgotten to include a datum associated with an input. Either way, the field 'data.extraneousDatums' contains a set of data hashes for these extraneous datums.
Data: {"extraneousDatums":["59196aef4b1fa3acae680ae7119efb2b5159bc1d2e74446d31ad511578fc5832"]}```

for this cbor:
```84a70081825820617c5041d9f041d39b50acf6325552ce088b7ec2aeb6fe32ea8c3fb2a5fb0f9501018383581d71ffff54dd7d1b69e8b388f612c6e7df437dee0aabcf35be641f3a31301a06316360582003db7a97f5f7a5867e4957f4acd146737c9deeea52acc7ee604b252979f7071782583901319723758f305d3171048358d7600d64912d6e83cd270055ec755070b4d98a7195aad84d4b76a6cd261edae312802acd4b0090c24d03b65a1a000f424082583901dc9598479f80e75a442b6dd84cc47096147011535887ddd8e8e4570c70f25ff6fd9adf330eb318ac48689baa721d52ded5cfda2c36540e061a92582a0a021a0002bd7d031a070b543b07582086e433fff32778331d6874487de13181911a7b67511598786f800a5514b81e0c08000b582065c349d0097a6213accaf0f634421b9e5d71990196e718121b4ef338539a7bd3a2008182582030776dc4d48c1ee2a744a8f48db8bf3de5b810450c13b7e3e7e4fced626304fe5840bc994c215b1723777b620f167cca10e5a8f052286e96a011a21547ebd1a550515517e6bc0c22f622b3b538b88723866acf5976831cbd14351823b9cd6db899050481d879825838dc9598479f80e75a442b6dd84cc47096147011535887ddd8e8e4570c70f25ff6fd9adf330eb318ac48689baa721d52ded5cfda2c36540e06d87c811b000000020c56b822f5a11902a2a1636d736781781d567966693a205377617020526571756573742076696120457465726e6c```

There is no such datum attached as far as I can see.

**Comment by MarcelKlammer** [comment] 2024-03-06 21:49
After digging deeper, it's likely a CSL issue: https://github.com/Emurgo/cardano-serialization-lib/issues/667

That leaves the initial issue: 

Using http to submit a transaction returns error:{"size":0,"timeout":0} on any error instead of the well defined responses we get from the socket connection.

**Comment by KtorZ** [comment] 2024-03-20 08:51
@MarcelKlammer I am unable to reproduce your `error:{"size":0,"timeout":0}` issue. Submitting through HTTP returns proper responses as far as I can tell. 

```bash
❯ curl -v http://127.0.0.1:1337 -d '{"jsonrpc":"2.0","method":"submitTransaction","params":
{"transaction":{"cbor":"84a30081825820a15ccf5d43c79f8f1923d8872574ac22ac13fa239f8ff77859799
41d821f482600018182581d6022ec2f9cdfa76198fcbc2cad3bf6fb6447b1577f449bfd7ec1f6d2cd1a00458897
021a001e8480a10081825820ff47ff7e9d01179eab07e0b391c422fb0e9c5b9d83873212976826d243c5cba0584
0445fde7ae79e1c6b4a6e84aa92cd7b5a67416473b3d32de860d237ffaa946c3d7d8bb3819927c40aa5d716c884
2bbdc9bcda581cba8f2fcef84e6dfd2aef8401f5f6"}}}' | jq

* Connected to 127.0.0.1 (127.0.0.1) port 1337
> POST / HTTP/1.1
> Host: 127.0.0.1:1337
> User-Agent: curl/8.4.0
> Accept: */*
> Content-Length: 465
> Content-Type: application/x-www-form-urlencoded

< HTTP/1.1 400 Bad Request
< Transfer-Encoding: chunked
< Date: Wed, 20 Mar 2024 08:47:37 GMT
< Server: Warp/3.4.0
< Content-Type: application/json; charset=utf-8
< Access-Control-Allow-Origin: *

{
  "jsonrpc": "2.0",
  "method": "submitTransaction",
  "error": {
    "code": 3117,
    "message": "The transaction contains unknown UTxO references as inputs. This can happen if the inputs you're trying to spend have already been spent, or if you've simply referred to non-existing UTxO altogether. The field 'data.unknownOutputReferences' indicates all unknown inputs.",
    "data": {
      "unknownOutputReferences": [
        {
          "transaction": {
            "id": "a15ccf5d43c79f8f1923d8872574ac22ac13fa239f8ff7785979941d821f4826"
          },
          "index": 0
        }
      ]
    }
  },
  "id": null
}
```

Do you have some minimal reproduction path? Could it be that this is a problem on your end, in some of the middleware you're using? Because there's no where in the codebase where Ogmios constructs an object with fields `"size"` and `"timeout"` and I have never observed this from the Haskell server stack (might it be for example some default response or something). So I find this quite puzzling to be honest 😓

**Comment by rhyslbw** [comment] 2024-06-28 22:58
Closing due to lack of reproduction or follow up from OP

**Closed by rhyslbw** 2024-06-28 22:58 UTC
Labels: waiting for author
